version: '3.8'
services:
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    container_name: postgres
      
  backend:
    build: 
      context: ../1.12/material-applications/example-backend/
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DATABASE=postgres
    ports:
        - 8080:8080
    depends_on:
      - db
      - redis
  frontend:
    build: 
      context: ../1.12/material-applications/example-frontend/
    ports:
        - 5000:5000
  redis:
    image: redis
    volumes:
        - /usr/src/app/
    #command: ["-d","redis-server" ,"--save","60","1"]

  
