version: '3.8'
services:
  training:
    build: ml-kurkkumopo-training
    volumes:
      - ./model:/src/model
      - ./image:/src/imgs
    
    container_name: training
      
  backend:
    build: 
      context: ml-kurkkumopo-backend
    volumes:
      - ./model:/src/model
    ports:
        - 5000:5000
    depends_on:
      - training
  frontend:
    build: 
      context: ml-kurkkumopo-frontend
    ports:
        - 3000:3000
    depends_on:
      - backend
