version: '3.8'
services:
  backend:
    build: 
      context: ../1.12/material-applications/example-backend/
    ports:
        - 8080:8080
  frontend:
    build: 
      context: ../1.12/material-applications/example-frontend/
    ports:
        - 5000:5000
  
